---
title: "DHIVER"
author: "Lou Dhiver"
format: html
editor: visual
---

```{r}
library(here)
library(tidyr)
library(dplyr)
library(ggplot2)
library(glue)
library(knitr)
```

## Introduction

###Question 1 : Load the data set.

```{r}
library(readr)
grades <- read_delim(here("data", "grades.csv"), delim = ",")
```

## Simple analyses

### Question 2 
```{r}
total_grades <- grades |>  
  select(grade) |> 
  summarise(total = n())
print(glue("The data set contains {total_grades$total} grades."))
```
### Question 3 
```{r}
number_students <- grades  |>   
  distinct(id)  |>  
  summarise(total=n())
print(glue("The number of student contained in the data set is {number_students$total}."))
```
### Question 4 

```{r}
students <- grades |>
  select(id,group) |>
  distinct() 
```

```{r}
  print(knitr::kable(head(students)))
```
### Question 5 
```{r}
## creating the variable student_per_group 
students_per_group <- students |> 
  group_by(group) |> 
  summarize(number_of_students = n_distinct(id))
print(students_per_group)

## creating the graphical representation 
ggplot(students_per_group, aes(x=group, y=number_of_students)) + 
  geom_bar(stat = "identity")+ 
  labs(title = "Number of students per group",
       x = "Group",
       y = "Number of students")
```

## Question 6 
```{r}
## Calculate the average grades 
average_grades_PAHA <- grades |> 
  filter (course == "Post-Apocalyptic History and Archaeology") |>
  group_by(group) |> 
  summarise(average_grade = mean(grade, na.rm = TRUE))
print (average_grades_PAHA)
```
```{r}
## graphical representation 
ggplot(average_grades_PAHA, aes(x = group, y = average_grade)) + 
  geom_col() + 
  labs(title = "Average Grades in Post-Apocalyptic History and Archaeology by Group",
       x = "Group",
       y = "Average Grade")
```
## Question 7 
```{r}
ggplot(grades, aes(x = grade, fill = factor(semester))) + 
  geom_density(alpha = 0.3) +
  labs(title = "Distribution of Grades by Semester",
       x = "Grades",
       y = "Density",
       fill = "Semester") +
  theme_minimal()  
```
The repartition of grades is much larger during the second semester (6 to 15), whereas during the 1 it is much more concentrated around the same values (6 to 13). 

## 3 Attendance analysis 
### Question 8 
```{r}
## calculate number of grades per students 
grades_per_student <- grades |> 
  group_by(id, group) |> 
  summarise(number_of_grades = n(), .groups = 'drop')
```

```{r}
## an extract 
grades_per_student_extract <- grades_per_student |>
  slice_tail(n = 5) |> 
  knitr::kable(caption = "Extract of grades per student data frame")
print(grades_per_student_extract)
```
```{r}
## creation of the markdown table 
summary_stats <- grades_per_student |> 
  summarise(
    min = min(number_of_grades),
    max = max(number_of_grades),
    average = mean(number_of_grades),
    median = median(number_of_grades)
  )

print(knitr::kable(summary_stats, format = "markdown", caption = "Summary Statistics of Grades per Student"))
```

### Question 9 
```{r}
## Filtering for the specific course asked and counting the number of grades 
grades_art_expression <- grades |>
  filter(course == "Art and Expression in a Post-Apocalyptic World") |>  
  group_by(id, group) |>  
  summarise(number_of_grades = n(), .groups = 'drop')  

## Extract of this data set 
grades_art_expression_extract <- grades_art_expression |>
  slice_tail(n = 5) |>
  knitr::kable(caption = "Extract of grades in Art and Expression in a Post-Apocalyptic World")
print(grades_art_expression_extract)
```

### Question 10 
```{r}
## regrouping students by same number of grades for Art and Expression in a Post-Apocalyptic World 
grades_distribution <- grades_art_expression |>
  group_by(number_of_grades) |>  
  summarise(number_of_students = n(), .groups = 'drop')
print(grades_distribution)

##Graphical representation 
ggplot(grades_distribution, aes(x = factor(number_of_grades), y = number_of_students)) +
  geom_col(fill = "forestgreen") +  # Use geom_col for bar plot
  labs(title = "Distribution of the Number of Grades in Art and Expression",
       x = "Number of Grades",
       y = "Number of Students") +
  theme_minimal()

```
### Question 11 


















